server:
  port: 8110
spring:
  application:
    name: cloud-config-center
  http: #防止读取配置文件中文乱码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaozhao0224/could-config.git #git路径
          search-paths:
            - could-config  #名称 https://blog.csdn.net/BuquTianya/article/details/78576745
          username: gaozhao0224  #我的文件是私有的所以写上账号密码
          password: mengzhong0224
      label: master  #分支
#  rabbitmq: #mq相关配置
#    host: 118.24.17.24
#    port: 15672
#    username: gzmq
#    password: gzmq
eureka:
  client:
    #\表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      #      defaultZone: http://eureka-gz01.com:1001/eureka/
      #集群版
      defaultZone: http://eureka-gz01.com:1001/eureka/,http://eureka-gz02.com:1002/eureka/,http://eureka-gz03.com:1003/eureka/

# rabbitmq相关配置，暴露bus刷新点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: '*'
