server:
  port: 7002
spring:
  profiles:
    active: dev

  application:
    name: nacos-production
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      # 字段策略 IGNORED:"忽略判断"(大部分情况只能全字段更新，否则需要处理的东西太多),NOT_NULL:"非 NULL 判断",NOT_EMPTY:"非空判断"
      insert-strategy: IGNORED
      update-strategy: IGNORED
      # 驼峰下划线转换
      column-underline: false
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    # 设置一级缓存级别为每次查询都清缓存
    local-cache-scope: STATEMENT
    # 关闭二级缓存
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl