spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: gz
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      url: jdbc:mysql://127.0.0.1:3306/gz-could?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 400
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #aop-patterns: com.fescotech.contract.controller.*
      filter:
        stat:
          log-slow-sql: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #配置超时时长
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  #feign调用超时时长  默认1s  改为5秒
  ConnectTimeout: 10000
  SocketTimeout: 10000