server:
  port: 1002
spring:
  application:
    name: server
eureka:
  instance:
    hostname: eureka-gz02.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      defaultZone: http://eureka-gz01.com:1001/eureka/,http://eureka-gz03.com:1003/eureka/
#      defaultZone: http://127.0.0.1:1000/eureka/

