# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 1234
  servlet:
    context-path: /gz

spring:
  profiles:
    active: dev
#    active: @profileActive@
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
snowflake:
  workerId: 0
  datacenterId: 6



