server:
  port: 9900

spring:
  application:
    name: contract
  profiles:
    active: dev


#主键生成策略
snowflake:
  workerId: 0
  datacenterId: 6


eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      #defaultZone: http://eureka-gz01.com:1001/eureka/
      #集群版
      defaultZone: http://eureka-gz01.com:1001/eureka/,http://eureka-gz02.com:1002/eureka/,http://eureka-gz03.com:1003/eureka/
